`timescale 1ns/1ps
`include "define.svh"
// Testbench: replay sim/layer_vectors.txt (generated by sim/gen_vectors.py)
//   W xx : host -> FPGA byte
//   R xx : expected FPGA -> host byte
module tb_layer;
    logic clk = 0;
    always #10 clk = ~clk;

    wire usb_p, usb_n, usb_pullup, led;
    Eyeriss_SoC_Top dut (
        .clk(clk), .rst(1'b0),
        .usb_d_p(usb_p), .usb_d_n(usb_n),
        .usb_pullup(usb_pullup), .led(led)
    );

    int fd, n_items, value, rx_idx, n_err, n_rd;
    byte kind;

    initial begin
        rx_idx = 0; n_err = 0; n_rd = 0;
        repeat (400) @(posedge clk);   // wait for POR
        fd = $fopen("sim/layer_vectors.txt", "r");
        if (fd == 0) begin
            $display("cannot open sim/layer_vectors.txt, run sim/gen_vectors.py");
            $finish;
        end
        while (!$feof(fd)) begin
            n_items = $fscanf(fd, " %c %h", kind, value);
            if (n_items != 2) break;
            if (kind == "W") begin
                dut.u_usb_uart.send_byte(value[7:0]);
            end else begin
                for (int t = 0; t < 5_000_000 && dut.u_usb_uart.tx_count <= rx_idx; t++)
                    @(posedge clk);
                n_rd++;
                if (dut.u_usb_uart.tx_count <= rx_idx) begin
                    $display("FAIL: timeout waiting for reply byte %0d", rx_idx);
                    n_err++;
                    break;
                end
                if (dut.u_usb_uart.tx_log[rx_idx] != value) begin
                    if (n_err < 10)
                        $display("  mismatch @reply %0d: hw=%02h expected=%02h",
                                 rx_idx, dut.u_usb_uart.tx_log[rx_idx], value);
                    n_err++;
                end
                rx_idx++;
            end
        end
        $fclose(fd);
        repeat (100) @(posedge clk);
        if (dut.u_usb_uart.tx_count != rx_idx) begin
            $display("FAIL: %0d unexpected extra reply bytes", dut.u_usb_uart.tx_count - rx_idx);
            n_err++;
        end
        $display("RESULT: %0d reply bytes checked, %0d errors -> %s",
                 n_rd, n_err, n_err == 0 ? "PASS" : "FAIL");
        $finish;
    end
endmodule
